#!/usr/bin/env python3
"""Deterministic generator for the committed synthetic C-MAPSS-shaped sample.

Hand-authored 3-unit trajectories with the same 26 whitespace-separated
columns as C-MAPSS (unit, cycle, 3 operating settings, 21 sensor channels),
clearly labeled synthetic via `#` comment headers (data-ethics.md §1/§2 —
this file is NOT NASA data; it only needs to be shape-compatible).

Outputs (next to this script, byte-stable across runs):
  train_FD001.sample.txt  run-to-failure trajectories (units 201..203)
  test_FD001.sample.txt   fleet observation cutoffs for the same units
  RUL_FD001.sample.txt    true remaining life at each cutoff

Run from this directory:  python3 generate-sample.py
"""

from __future__ import annotations

import random
from pathlib import Path

SEED = 42

# (unit_id, life_cycles, degradation_start_frac, cutoff_cycle) — cutoff 0 = no cutoff
UNITS = [
    (201, 200, 0.45, 80),  # NX-E201 healthy at cutoff (deep remaining life)
    (202, 160, 0.30, 140),  # NX-E202 degrading — alert fixture at cutoff
    (203, 60, 0.20, 6),  # NX-E203 insufficient history at cutoff (< MIN_CYCLES)
]

# Healthy baseline values per sensor channel (s1..s21), sitting inside the
# FD001 operating envelope (s1=T2 518.67, s3=T30, s4=T50, s9=phi, s14=W32…).
# Hand-authored to be shape- and distribution-compatible — NOT NASA data.
BASELINES: dict[int, float] = {
    1: 518.67,
    2: 641.8,
    3: 1580.0,
    4: 1390.0,
    5: 14.62,
    6: 21.6,
    7: 554.0,
    8: 2388.05,
    9: 9050.0,
    10: 1.3,
    11: 47.2,
    12: 522.8,
    13: 2388.1,
    14: 8110.0,
    15: 8.36,
    16: 0.03,
    17: 399.5,
    18: 2388.0,
    19: 100.0,
    20: 38.3,
    21: 23.55,
}

# Degradation sign and total excursion per channel (matched to each channel's
# observed FD001 spread), applied from degradation_start to end of life with a
# power-law ease-in (late-life acceleration — real turbofan degradation is
# anything but linear near removal).
DRIFT: dict[int, tuple[int, float]] = {
    2: (+1, 2.4),
    3: (+1, 36.0),
    4: (+1, 50.0),
    7: (-1, 4.5),
    8: (+1, 0.45),
    9: (+1, 190.0),
    11: (+1, 1.3),
    12: (-1, 4.4),
    13: (-1, 0.4),
    14: (+1, 180.0),
    15: (+1, 0.22),
    17: (-1, 11.0),
    20: (+1, 1.1),
    21: (-1, 0.65),
}

DRIFT_POWER = 3.0

# Per-channel measurement noise amplitude (a fraction of each channel's FD001
# variation) — enough to look like measurements, small enough to keep the
# degradation signal clean.
NOISE: dict[int, float] = {
    2: 0.18,
    3: 2.0,
    4: 2.5,
    7: 0.3,
    8: 0.025,
    9: 7.0,
    11: 0.1,
    12: 0.25,
    13: 0.025,
    14: 6.0,
    15: 0.015,
    17: 0.5,
    20: 0.06,
    21: 0.04,
}

HEADER = "# SYNTHETIC SAMPLE — hand-authored 3-unit trajectory data for CI/offline dev."
HEADER2 = "# NOT NASA C-MAPSS data (data-ethics.md): shape-compatible, generated by generate-sample.py (seed 42, deterministic)."


def fmt(x: float) -> str:
    """Compact fixed-width-ish formatting, stable across runs."""
    return f"{x:.3f}".rstrip("0").rstrip(".") if abs(x) < 1e6 else f"{x:.1f}"


def sensor_value(rng: random.Random, sensor: int, frac: float) -> float:
    """frac = elapsed life fraction in [0, 1]."""
    base = BASELINES[sensor]
    noise = rng.uniform(-NOISE.get(sensor, 0.0), NOISE.get(sensor, 0.0))
    return base + noise


def degrading_value(rng: random.Random, sensor: int, frac: float, start: float) -> float:
    base = BASELINES[sensor]
    noise = rng.uniform(-NOISE.get(sensor, 0.0), NOISE.get(sensor, 0.0))
    sign, span = DRIFT.get(sensor, (0, 0.0))
    if frac <= start:
        return base + noise
    t = (frac - start) / (1.0 - start)
    # power-law ease-in — degradation accelerates sharply toward failure
    return base + noise + sign * span * (t**DRIFT_POWER)


def build_rows(rng: random.Random) -> dict[int, list[str]]:
    rows: dict[int, list[str]] = {}
    for unit, life, start, _cutoff in UNITS:
        out: list[str] = []
        for cycle in range(1, life + 1):
            frac = cycle / life
            set1 = rng.uniform(-0.009, 0.009)
            set2 = rng.uniform(-0.001, 0.001)
            fields = [str(unit), str(cycle), f"{set1:.4f}", f"{set2:.4f}", "100.0"]
            for sensor in range(1, 22):
                if sensor in DRIFT:
                    v = degrading_value(rng, sensor, frac, start)
                else:
                    v = sensor_value(rng, sensor, frac)
                fields.append(fmt(v))
            out.append(" ".join(fields))
        rows[unit] = out
    return rows


def main() -> None:
    here = Path(__file__).resolve().parent
    rng = random.Random(SEED)
    rows = build_rows(rng)

    train_lines = [HEADER, HEADER2]
    test_lines = [HEADER, HEADER2]
    rul_lines = [HEADER, HEADER2, "# unit  trueRulAtCutoff"]
    for unit, life, _start, cutoff in UNITS:
        if cutoff == 0:
            cutoff = life
        train_lines.extend(rows[unit])
        test_lines.extend(rows[unit][:cutoff])
        rul_lines.append(f"{unit} {life - cutoff}")

    (here / "train_FD001.sample.txt").write_text("\n".join(train_lines) + "\n")
    (here / "test_FD001.sample.txt").write_text("\n".join(test_lines) + "\n")
    (here / "RUL_FD001.sample.txt").write_text("\n".join(rul_lines) + "\n")
    print("sample regenerated (deterministic, seed 42)")


if __name__ == "__main__":
    main()
